export type minMaxImg = [any, any, any, any]
            | [any, any, any, any, any]
            | [any, any, any, any, any, any]
            | [any, any, string, any, any, any, any]
            | [any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, string, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any]
            | [any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any, any];